lostcarpark/conclar

src/App.css, src/config.json
Made some minor CSS changes:
- Removed Calibri from list of fonts as it was rendering without smoothing on Firefox for Linux. Could possibly be put back if the order was changed.
- Added "break-inside: avoid" to participants in People, to prevent thumbnail and name from splitting across columns.
- Added table of contents and section headings.
Also undid a config change I was using for testing.
=> Minor CSS fixes.

src/App.css, src/components/FilterableProgram.js
Push the new button/checkbox right.  They're starting to take up some space and maybe should be made into more of a toggle, possibly from the React side.
Note that CSS classes can't start with numbers, so I renamed it, hopefully correctly---but not the storage key, which you may want to change, too, for consistency.
=> Rename illegal class and style

README.md, src/components/FilterableProgram.js, src/config.json, src/model.js, src/utils/LocalTime.js
This hides the Show Past Items button when the con is too far in the past or future for it to matter.
=> Add past item logic

README.md, src/components/FilterableProgram.js, src/config.json
Config settings and code to turn off searching in multiselects (see [my bug](https://github.com/mcdemarco/conclar/issues/6) for reasons), and also to include tag configuration for when they aren't split.
=> Make multiselect searching configurable, and add plain tag config

src/App.css, src/components/ProgramItem.js
These changes are necessary to move durations inline with location.  The css also actively does so, but you can comment out that class section to not do so.
For Boskone I'm also configuring the label like this:
```
"DURATION_LABEL": " (@mins mins)"
```
That's not in this PR, but I'm mentioning it in case you like it and want to make it the default.
=> Move duration inline

src/utils/LocalTime.js
When Grenadine passes items without dates, they get partly processed into an "Invalid Date" day in the schedule (with no items).  The string is just more Date object jankiness, not an intentional error message.  This change removes that string, but doesn't otherwise affect processing.
=> Don't pass Invalid Date to the UI

src/ProgramData.js, src/components/Participant.js, src/components/ProgramItem.js
This information was lost in the unification of persons.  I added it back on as an attribute of `item` with the appropriate person's `id`, which is then passed into Participant at the appropriate time(s) as a boolean prop.
I considered customizing the moderator text and handling other Grenadine roles, but since "moderator" is the only Zambia role and is extremely hard-coded, I did not put in any effort in that direction.  Maybe if Zambia gets more flexible this code could be expanded.
=> Restore Zambia-style moderators and add Grenadine-style moderators

README.md, src/components/Person.js, src/components/ProgramItem.js, src/config.json
This code passes in DOMPurify options from the config file.  Different values are supported for item descriptions and bios (the only places DOMPurify is currently used).  This handles an issue Boskone is having with some data cut and pasted into Grenadine, by using "FORBID_ATTR": ["style"] on descriptions.  I think there's also a use case for editing out more intentional bits of the source data, like unusual but technically "safe" HTML in bios.  
Documented in the readme.
=> Allow configuration of DOMPurify options

src/components/ItemById.js
A small fix to make item linking work with Grenadine data, where IDs are integers.  There's already similar code in Person.js for participant linking.
=> Fix for linking IDs with Grenadine data where IDs are not strings

src/components/AppRoutes.js
This is a minor edit to add routes for index.html.  The fact that index.html returned an (internal, not HTTP) error message about not finding index.html disturbed one of our developers.
=> Fix for "error" returned when hitting index.html directly

package-lock.json, package.json, src/ProgramData.js, src/components/Day.js, src/components/TimeSlot.js, src/utils/LocalTime.js
This change uses the Temporal API, which is a proposed new date handling extension for JavaScript. As browsers don't yet support it, it has been added via the `@js-temporal/polyfill` library.
During processing, each program item has a `dateAndTime` field populated with is a `Temporal.zonedDateTime` field in the convention timezone. When displaying the output, can use the `withTimeZone` method to convert to the browser timezone, which cuts down the complexity of the code considerably.
It also converts the local and convention zonedDateTime values to PlainDate values. Comparing these lets us check if the item is on the previous or next day, and add a label accordingly.
I haven't looked at the code that checks if convention is currently ongoing, but I think this could also be considerably …
=> Use Temporal API for more robust date handling.

src/ProgramData.js
Tags were not getting separated for Reclamation. ProgramData.js was not seeing the `SEPARATE` property of TAGS in config.
Changed from using `in` to `hasOwnProperty` for checking presence of property, and seems to have resolved issue, but not sure why `in` stopped working when it had previously.
Also some minor indentation and formatting changes.
=> Changed tags to use 'hasOwnProperty' as IN was misbehaving.

README.md, docs/conclar_file_specs.md, src/ProgramData.js, src/components/FilterableProgram.js, src/components/ProgramItem.js, src/config.json, src/utils/Format.js
Now allows tags in program file to be specified as objects instead of strings.
If string tags are used, they will be parsed into objects internally.
If objects used, should follow the format: `{ "value": "tag ID", "category": "tag category", "label": "label to display" }`
Also adds HIDE property to TAG in config, to allow a tag category to not have a drop-down, though the tags still appear on program items.
=> Allow tags to be specified as strings or objects.

src/components/PersonLinks.js
Fix an issue that links without protocol were interpreted as local links. Fix is to not display links unless protocol included.
=> Require http/https on participant links.

src/ProgramData.js, src/components/FilterableProgram.js, src/components/TagSelect.js, src/components/TagSelectors.js
- Move tag selection components off FilterableProgram component into TagSelectors, which contains TagSelect components that can be reused on participants.
- Alter ProcessTags function to not refer explicitly to program tags, so it can be reused for participant tags.
This change is to prepare for a future change to add participant tags.
=> Add components for tag drop-downs and make tag processing generic.

README.md, docs/conclar_file_specs.md, src/App.css, src/ProgramData.js, src/components/People.js, src/components/Person.js, src/components/PersonLinks.js, src/config.json, src/model.js
Have added tags for people as follows:
- Added tags to people file format (tags take same format as program tags).
- Added TAG options under PEOPLE in config. Takes same format as program tag settings, except doesn't have DAY_TAG options because that would make no sense.
- Added TagSelector component to People page, and filter people by tags.
- Added tag listing under name on Person page.
- Added CSS settings for formatting person tags.
Not related to tags, but have added back button to person page, as there wasn't a clear route back previously, and pressing browser back button was a little clunky.
=> Add tags to people page.

src/App.css, src/components/FilterableProgram.js, src/components/People.js
This change tweaks the search box as follows:
- Change input type from "text" to "search". In most browsers, they are displayed the same, but some browsers benefit from knowing it's a search box.
- Tweak search CSS to make it more like tag selectors.
=> Change search boxes to search input type. Update styling.

README.md, src/App.css, src/ProgramData.js, src/components/ProgramList.js, src/components/Settings.js, src/components/TimeSlot.js, src/config.json, src/model.js, src/utils/LocalTime.js
Show time zone short label after times.
By default will only be shown when local time is displayed.
Added new setting to Settings page to select when to show timezone. Defaults to "Show timezone if local time shown".
Added new config option to let user change when to display timezone.
Added config options for new Settings page labels.
This should resolve #114.
=> Show time zone after time.

src/ProgramData.js, src/components/PersonLinks.js
Revert the moderator code to the old code as the new didn't work.
In the link loop, change break to continue otherwise the loop stops and some links won't display.
=> Revert moderator code. Fix links loop.

src/App.css
- Added space around QR codes.
- Changed units for sharing section from em to rem.
- Changed colours of "Reset" and "Add all" buttons to use variables from navigation buttons. This keeps button colours consistent by default but makes it easy to customise if required.
=> CSS tweaks

src/ProgramData.js, src/components/Day.js, src/components/ProgramItem.js, src/components/ProgramList.js, src/components/TimeSlot.js, src/utils/LocalTime.js
- Added timeSlotCache to store numeric index of time slots.
- Added conventionTimeCache and localTimeCache to store rendered time text.
- Use numeric timeslot indexes whenever possible instead of dateAndTime.
- Store timeSlotCache, conventionTimeCache and localTimeCache in LocalStorage for reuse in later sessions.
These changes have yielded a minor performance improvement.
=> Time slot cache

src/components/FilterableProgram.js
There's a bug causing Chicon to display no items when filter selected. I haven't managed to reproduce, but I think it might be due to non integer values in the display limit. Have added integer parsing to try to resolve.
=> Added integer parsing to try to fix bug displaying filtered items.

src/App.css, src/components/Day.js, src/components/TimeSlot.js
- Add `position: sticky` to date and timeslot labels so the date and time of the currently viewed item is easily visible.
- Add background colour to date heading, so it will cover items scrolling under it.
- Added time-wrapper `div` around times so they can be themed as a block.
- Added `z-order: -1` to time-wrapper header so it scrolls beneath date header.
Unrelated change to remove id from date tag, as it contains spaces, which aren't allowed in IDs, and it isn't actually used in the application.
=> Make date and timeslot labels sticky

src/ProgramData.js
Program failed to display, and error shown on console if any items had no participants.
=> Prevent error if program item has no participants.

src/App.css, src/ProgramData.js, src/components/Day.js, src/components/ItemLink.js, src/components/ProgramItem.js, src/components/ProgramList.js, src/components/TimeSlot.js, src/config_example.json, src/utils/LocalTime.js
Links can now be configured with whether they should be enabled before, during or after the item.
Sometimes streaming links aren't a link to the specific item, but to a stream for the room the item is in. People can get confused if the click on a "Click to view stream" link for an item that isn't currently on and see a different item. To avoid this confusion, we can now configure the streaming links to only be enabled during the item.
Similarly, replays aren't typically available until after the item has finished.
If no `WHEN` is configured, it is assumed to be always enabled.
=> Allow configuring when links should be enabled

src/App.css, src/components/AppRoutes.js, src/components/Header.js
Currently the footer will hover in the middle of the page if the page doesn't fill the screen.
This change will formats the App as a CSS grid, set to fill the display viewport.
The header and footer rows are set to "auto" height, so will take minimum required space. The content row is set to `1fr` (fractional unit), which will cause it to expand to fill available space.
If the page is taller than the screen, it will scroll normally.
As part of this, I've moved the navigation into the header.
=> Push footer to bottom of screen

README.md, src/App.css, src/components/FilterableProgram.js, src/config_example.json, src/model.js
Adds a new filter drop-down with a lit of times. Items before selected time on first day in filter will be hidden.
This is to improve accessibility and reduce the number of items screen reader users have to go through.
=> Add dropdown with times to hide items before

src/components/FilterableProgram.js
Hide before drop-down was not working because:
1. Used onClick instead of OnChange
2. Did not have keys on list items
=> Fix hide before drop-down in Chrome

src/components/Participant.js
Testing with Wave reports images with alt text the same as nearby text. Making alt text blank for participant image in programme item to correct.
=> Make alt text on participant image in program item blank

src/components/FilterableProgram.js
Fixes a problem with incorrect first day being used for "select time" drop-down.
=> When no day selected, take day from first programme item if possible.

src/components/Navigation.js
Previously if Information link was not present, and empty button would be displayed. However, some conventions may have an information page elsewhere, so may not want this in the programme guide. This change will not show the button if the NAVIGATION.INFO config item is not present.
=> Hide Information navigation link if not present in configuration.

README.md, src/components/AppRoutes.js, src/components/FilterableProgram.js, src/components/LocationProgramme.js, src/components/ProgramItem.js, src/config_example.json
This change adds a `/loc/room name` link for each room. It also supports multiple rooms with `/loc/room 1~room 2`.
When a selection is made from the Location drop-down, the URL is updated to reflect this.
This goes some way to solving #170, though it would be nice to make it work for all selection criteria.
=> Provide Location Routes so Room Programme can be linked to
