src/App.js
src/components/Participant.js
src/components/Person.js

Default from name fields if not in datafile.

Added 'sortname' field to person. 

---

README.md
public/manifest.json

Just some minor textual edits, including a non-generic-React home page app name.

Correct and improve README and manifest

---

src/App.css
src/components/Participant.js
src/config.json

Added a setting and code for a user-specified participant image placeholder.  You can see it in action at http://test.mcdemarco.net/conclar/.

Profile img placeholder

---

src/App.css
src/components/FilterableProgram.js
src/components/ProgramList.js

Make the layout a bit more responsive with more consistent use of flexbox.

Flex layout improvements

---

src/App.css
src/App.js
src/components/NotFound.js
src/components/Person.js

Add error messages for bad root paths and bad person IDs.  I don't think there are any other error cases, but if more come up they can probably be handled as in Person.js.

Error handling

---

src/App.css
src/App.js
src/components/Participant.js
src/components/Person.js
src/components/TimeSlot.js

I was working with some slightly bad data and ran across a few error conditions to fix, plus added some general image 404 handling and a fix for the default head image when called from subdirectories (that is, people page schedules).  Also I added image handling for Grenadine's export data format, which is otherwise very close to Konopas' data format.

Image and other error handling

---

docs/conclar_file_specs.md
package.json
public/.htaccess
src/App.css
src/components/Participant.js
src/components/ProgramItem.js
src/config.json

The Cap prod site does not use a sub-folder, so I removed that.
I also add the item duration to the item description. The duration is in minutes and uses the 'mins' field from the json data.

Changed to Cap prod site and added duration to item description.

---

src/App.css
src/components/FilterableProgram.js
src/config.json
src/model.js
src/utils/LocalTime.js

I added a filter for hiding past items, with a bit of wiggle room for what counts as "before now".  
This PR includes the bug fix from the previous one, for my convenience.  I can rebase if you need that.

Show past items filter

---

src/components/FilterableProgram.js
src/model.js

I was just going to tell you about the typo, but then I saw it had spread to more than one file.

Fix typo that broke 12 hour time

---

src/components/Person.js
src/config.json

Just a minor change to make "People: `<participant name>`" optional/styleable.

Configure person page header title and wrap in span/class

---

README.md
src/App.css
src/components/AppRoutes.js
src/components/Participant.js
src/components/ProgramItem.js
src/components/UnfilterableProgram.js
src/config.json

This is a relatively simple, one might even say hacky, implementation of a non-interactive version of the schedule using a config value and a slimmed-down schedule filtering component.  Requested by people at Boskone who are not me.

Uninteractive

---

src/components/ProgramItem.js
src/config.json

We also need a signup link for our sign up items.  It might be a good idea to un-hard-code these link types and just allow an array in the config, but I wasn't sure three was the charm for that.

Add signup link

---

README.md
package-lock.json
package.json
src/App.css
src/components/AppRoutes.js
src/components/Day.js
src/components/ItemById.js
src/components/ProgramItem.js
src/components/ProgramList.js
src/components/TimeSlot.js
src/config.json

- Add permalink icon using react-icons.
- Add new route for program item ID.
- Add Link around permalink icon.
- Add new ItemById component.
- Add property to ProgramItem to force it to be expanded.
- Add CSS class to float permalink icon right.
- Add SHOW_PERMALINK and PERMALINK_TITLE to config.
- Add new settings to Readme.

Add Permalink Icon to each program item

---

src/App.css

Small but cute change to style the permalink icon.

Style permalink icons (with variables)

---

src/App.css
src/components/FilterableProgram.js
src/components/MySchedule.js
src/components/Navigation.js

The two improvements are for small screen layout, and highlighting the selected page using React NavLink in place of Link (plus the appropriate css w/color vars).

Improve navigation styles

---

docs/conclar_file_specs.md

Just a minor edit to the docs.

Forgot to document the signup link

---

src/components/People.js

Some tidying up of the code on the People component.
- Removed unnecessary handler functions.
- Changed array push to array map.

People sort

---

docs/conclar_file_specs.md

Some minor corrections noticed by a Boskone volunteer.

Fix some objects incorrectly shown as arrays in doc/spec

---

docs/conclar_file_specs.md
src/App.css
src/ProgramData.js
src/components/FilterableProgram.js
src/components/Location.js
src/config.json

Added additional check for moderator and updated the note for it, added a space to the location display because multiple locations for a session were displaying right next to each other with no space, and updated the css so that next day/previous day would go to next line.

Small fixes - moderator, space in location, note, css update

---

README.md
docs/conclar_file_specs.md
package-lock.json
package.json
src/App.css
src/App.js
src/ProgramData.js
src/components/AppRoutes.js
src/components/Day.js
src/components/FilterableProgram.js
src/components/Location.js
src/components/MySchedule.js
src/components/Navigation.js
src/components/Person.js
src/components/PersonLinks.js
src/components/ProgramItem.js
src/components/ProgramList.js
src/components/Settings.js
src/components/ShowPastItems.js
src/components/TimeSlot.js
src/components/UnfilterableProgram.js
src/config.json
src/model.js
src/utils/LocalTime.js

This change is mainly about timezones and time handling.
The biggest UI change is the addition of a Settings page. This moves the Show Local Time and 12 Hour Time off the Program page, and adds the ability to select the local timezone to display.
It also completes move to Temporal API for time handling and calculations.
Internally all times are stored as Temporal.ZonedDateTime.
This vastly simplifies calculations such as checking if during convention.
This should resolve issues #87 and #97.

Timezone select

---

docs/conclar_file_specs.md

Just a problem with the indentation of the file format document, which turned out to be caused by a tab where there should have been spaces.

Tag object and hiding

---

docs/conclar_file_specs.md
src/components/PersonLinks.js

Use a globe as the icon for "website" link.

Add website icon of a globe

---

src/config.json

I accidentally left a set of local test data files I'm using in the config file. These are not in the repository, so it makes it difficult for anyone to test. I would like to create a set of local data files with invented data for testing, but for now I think the best thing to do is revert to the previous external data files.

Restore previous data files.

---

README.md
src/App.css
src/components/FilterableProgram.js
src/components/People.js
src/components/ResetButton.js
src/config.json
src/model.js

Changes to the "Reset filters" button:
- Change label from X icon to label taken from FILTER.RESET.LABEL in config.
- Move button below filter controls.
- Style as button, similar to navigation buttons.
- Hide button when no filters in use.
Hopefully this will correct issue #110.

Change reset filters button from X to configurable label.

---

README.md
src/ProgramData.js
src/components/AppRoutes.js
src/components/FilterableProgram.js
src/components/Loading.js
src/components/PersonLinks.js
src/components/ProgramList.js
src/components/TimeSlot.js
src/config.json
src/model.js
src/utils/LocalTime.js

Changes to improve performance
- Changed date generation for date tag value
- Added loading screen
- Added "maximum items displayed" drop-down
- Additional change from using locale functions to get day name for tags, to using a static list in config, which took another half second off processing time. This has the disadvantage that it needs a list in config, but has the advantage that the day names are fully customisable.

Performance Optimisation.

---

src/ProgramData.js

- Minor change to override sort name if blank.
- Remove participant from program item if not on master participant list.

Remove participants if they are on program item but not master list

---

README.md
package-lock.json
package.json
src/App.css
src/ProgramData.js
src/components/FilterableProgram.js
src/components/ProgramList.js
src/components/TagSelect.js
src/components/TagSelectors.js
src/config.json

- Added "Show more" button when not all program items displayed.
- Pressing adds a batch of configurable size (default 50) to the display.
- Added config settings for labels and number of items to add.
- Reset displayed items back to current selection when filters reset or changed.

Show more button

---

src/components/MySchedule.js
src/model.js

- Added Expand All and Collapse All buttons to MySchedule.
- Changed model to allow My Schedule items to be expanded/collapsed.
- MySchedule items remain expanded if you go back to full program.

Add expand all/collapse all to My Schedule.

---

src/ProgramData.js
src/components/AppRoutes.js
src/components/Debug.js
src/components/Timer.js
src/config.json
src/model.js

Change to fetch without disabling cache when loading first time. This will load cached data (if available) when app loads. First refresh will then overwrite with fresh data (if online).

Better handling when offline.

---

src/components/AppRoutes.js

- Make the TheApp variable a local variable of AppRoutes function.
- Rename to theApp for consistent camelCase naming.
- If debugging enabled in config, add `debug-mode` class to App component div, so that child components can be moved down with CSS.

Move TheApp variable inside component function.

---

src/App.css
src/darkmode.css

In dark mode participant background was too similar to the name links.

Correct participant background for dark mode.

---

src/App.css
src/components/FilterableProgram.js
src/components/People.js
src/components/ProgramItem.js
src/components/Settings.js

Correct accessibility issues reported by Wave.
Most issues resolved by adding label.

Add labels for accessibility.

---

src/darkmode.css

Additional issue with dark mode, insufficient contrast on program item time on mobile.

Fix background colour of time on mobile.

---

src/ProgramData.js

Fix failure to load programme data if an invalid person is present in an item.

Invalid person fix in main

---

src/components/FilterableProgram.js

Change how time filter applies when day filters aren't explicitly selected. It should always apply to the first day being displayed.

Make time filter always apply to the first day being displayed.

---

src/components/AppRoutes.js
src/components/ThemeSelector.js

Some basic formatting tidy ups.
In ThemeSelector, correct indentation.
In AppRoutes, move conditional logic out of react component into a variable.

Tidy up formatting.

---

README.md
src/App.css
src/components/Header.js
src/components/HelpText.js
src/config_example.json
src/model.js

This change adds a help text message to the top of the application.
- Currently this will show a message to visitors: Welcome to ConClár. You can use the checkboxes next to programme items to make a personal schedule. You can view this on the My Schedule page, and share to other devices.
- When they have made some selections, it will show: You may share your personal schedule to other devices using the QR codes on the My Schedule page.
There is a dismiss button to dismiss each message. The application will track which messages have been dismissed in local storage.

Add help text box to top of page.

---

README.md
src/components/MySchedule.js
src/config_example.json

Add a new configuration setting containing text to display on the My Schedule page when there are no programme items selected.

Text when My Schedule empty.

---

src/components/HelpText.js

Accidentally left some debugging statements in the code.

Remove debugging from helptext component.

---

README.md
public/index.html
src/App.css
src/ProgramData.js
src/components/AppRoutes.js
src/components/Footer.js
src/components/Participant.js
src/components/ProgramItem.js
src/components/ShareLink.js
src/config_example.json
src/darkmode.css

I have gone through all the commits to the Glasgow fork for ConClár that aren't in the main branch. I have ignored any that were specific to Glasgow, such as colour changes or message text, and identified the commits with application changes, or style changes that are not specific to Glasgow theming.
This pull request is to merge those changes into the main branch.

Glasgow changes

---

src/ProgramData.js

I forgot that there were two slightly different pieces of logic for loading separate schedule and people files, and for loading a single combined file. My last change made the Info file load during data refresh, but I only added to the load logic for two separate files.
This change corrects by adding to the load single file logic.

Was not loading Info file if single schedule and participants file
